export const workDescription = () => {
  return {
    work: {
      vincit: {
        company: 'Vincit Oyj',
        title: 'Software Developer',
        years: '2022-present',
        description: [
          'Working as a senior full-stack developer in a public sector project for HSL (Helsingin seudun liikenne) to create new public transport register for them.',
          "- The new platform is a crucial part of HSL's daily operations, and it will replace an old system build in the early 2000s.",
          '- The project comprises of React frontend connected to Hasura and multiple microservices written in Java.',
          '- Quickly took grasp of multiple new technologies like Spring Boot and Hasura.',
          '- The JORE4 source code is available in HSL GitHub.',
          '\n',
          'Worked as a senior full-stack developer in a fast-paced hospitality project to create a new website, a custom booking engine and a new services website for a prominent Finnish hospitality chain.',
          '- Worked on the booking engine and website which are built with .NET/C# and NextJS',
          '- Integrations with multiple other systems, such as SmartHotel and Oracle Opera',
          '- After the initial release, I led the development of administration software for the new booking engine',
          '- Initial analytics revealed that after the release the conversion rate had gone up by up to 100% for mobile users',
          '\n',
          'Before that, I worked with a team planning, researching, and developing proof-of-concept software for a client in the e-sports industry.',
          '- Researching and utilising multiple different e-sports data feed APIs',
          '- The software will utilise machine learning and generative AI',
          '\n',
          "I developed Vincit's internal payroller software, which our salary team uses to calculate the correct bonuses, provisions, and other benefits for workers.",
          '- Integrations with multiple other systems used by the salary team',
          '\n',
          "I worked for a well-known company in the energy sector as a contractor, developing a customer information system (CIS) used by many of Finland's largest energy companies.",
          "- Worked on the reporting module of the customer's flagship CIS product",
          '- Worked on modifying the module for a new foreign market',
          "- Developed a cutting-edge reporting microservice for a customer's new software product",
        ],
        technologies: [
          'C#',
          'ASP.NET',
          'TypeScript',
          'React',
          'Next.js',
          'Storyblok',
          'PostgreSQL',
          'Entity Framework',
          'Azure',
          'AWS',
          'Docker',
          'Terraform',
          'Python',
          'Express.js',
          'Kubernetes',
          'Java',
          'Spring Boot',
        ],
      },
      nomicam1: {
        company: 'NomiCam Oy (now part of Amazon Ring)',
        title: 'Software Developer',
        years: '2020-2022',
        description: [
          '- Wrote and maintained software for NomiCam Dynamic',
          "- Implemented improvements and bugfixes for NomiCam's MIP",
          "- Developed plugins for NomiCam's MIP software using C#",
        ],
        technologies: [
          'C#',
          '.NET Framework',
          'TypeScript',
          'React',
          'Azure',
          'Docker',
        ],
      },
      nomicam2: {
        company: 'NomiCam Oy',
        title: 'Junior Software Developer',
        years: '2019-2020',
        description: [
          "- Implement CI pipeline for NomiCam's MIP software",
          '- Build a remote control for an industrial robot using .NET Core',
          "- Developed plugins for NomiCam's MIP software using C#",
        ],
        technologies: ['C#', 'C++', '.NET Framework', 'Docker'],
      },
      nomicam3: {
        company: 'NomiCam Oy',
        title: 'Software Developer Trainee',
        years: '2019-2019',
        description: [
          "- Developed plugins for NomiCam's MIP software using C#",
          "- Wrote user documentation for NomiCam's MIP plugins",
        ],
        technologies: ['C#', 'C++', '.NET Framework'],
      },
    },
    education: {
      masters: {
        university: 'Tampere University',
        years: '2021-2024',
        level: 'Master of Science in Technology',
        major: 'Software Engineering',
        subject: 'Software, Web, and Cloud',
      },
      bachelors: {
        university: 'Tampere University',
        years: '2018-2022',
        level: 'Bachelor of Science',
        major: 'Computer Science',
        subject: 'Software Engineering',
      },
    },
    certification: {
      azureFundamentals: {
        name: 'Microsoft Certified: Azure Fundamentals',
        issuer: 'Microsoft',
        issued: 'Feb 2024',
        credentialId: '413A181C942BAC00',
        url: 'https://learn.microsoft.com/api/credentials/share/en-us/JoonasHiltunen-2330/413A181C942BAC00?sharingId',
      },
    },
    project: {
      flightrandomizer: {
        name: 'Flight randomizer',
        description: [
          'A simple tool for selecting a random flight from an airport',
          '- Created using Next.js with TypeScript and Chakra UI library',
          '- Utilises data from FlightRadar24 APIs for finding airports and flights',
          '- Deployed using Vercel',
        ],
        url: 'https://flights.jontzi.com',
        git: 'https://github.com/Jontzii/FlightRandomizer',
        technologies: [
          'React',
          'TypeScript',
          'Next.js',
          'Node.js',
          'Chakra UI',
          'Vercel',
        ],
      },
      getaroom: {
        name: 'Get a Room!',
        description: [
          'A progressive web app for booking a meeting room on the fly.',
          '- Utilises Google Workspace and Google Calendar APIs',
          '- Can be deployed for any organisation using Google Calendar',
          '- Deployed to Google Cloud Run',
        ],
        url: 'https://getaroom.vincit.com',
        git: 'https://github.com/Vincit/get-a-room',
        technologies: [
          'React',
          'Node.js',
          'TypeScript',
          'MUI',
          'Google Cloud',
          'Docker',
        ],
      },
    },
    other: {
      interests: ['Cloud Computing', 'Cloud Architecture'],
      hobbies: ['Gaming', 'Aviation', 'Movies', 'Badminton'],
    },
  };
};
